fuse:
  dir: '${FLY_LITEFS_DIR}'

  debug: false

data:
  dir: /data/litefs

exit-on-error: false

lease:
  type: 'consul'
  candidate: ${FLY_REGION == 'iad'}
  advertise-url: 'http://${HOSTNAME}.vm.${FLY_APP_NAME}.internal:20202'

  consul:
    url: '${FLY_CONSUL_URL}'
    key: 'lifefs/${FLY_APP_NAME}'