name: 🚀 Deploy
on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - content/**
      - .github/workflows/refresh-content.yml
      - README.md

  pull_request:
    paths-ignore:
      - content/**
      - .github/workflows/refresh-content.yml
      - README.md

jobs:
  deploy:
    name: 🚀 Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: 📁 Checkout Repo
        uses: actions/checkout@v3

      - name: 📖 Get App Name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: 'fly.toml'
          field: 'app'

      - name: 🚀 Deploy Staging
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args:
            'deploy --remote-only --app ${{ steps.app_name.outputs.value }}-staging'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: 🚀 Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args:
            'deploy --remote-only'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}