name: Refresh Markdown Content
on:
  push:
    branches:
      - main
    paths:
      - content/**


jobs:
  refresh:
    name: Refresh Content Webhook
    runs-on: ubuntu-latest
    steps:
      - uses: distributhor/workflow-webhook@v2
    env:
      webhook_url: ${{ secrets.REFRESH_WEBHOOK_URL }}
      webhook_secret: ${{ secrets.REFRESH_WEBHOOK_SECRET }}
      webhook_auth: ${{ secrets.REFRESH_WEBHOOK_AUTH }}