name: Refresh Markdown Content
on:
  push:
    branches:
      - main
    paths:
      - content/**

jobs:
  refresh:
    name: Refresh Content
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "2"

      - name: 📁 Get Changed Files in Content Directory
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: content/**
          include_all_old_new_renamed_files: true

      - name: 🪝 Refresh Webhook
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          webhook_url: ${{ secrets.REFRESH_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.REFRESH_WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.REFRESH_WEBHOOK_AUTH }}
          data: '{"added": "${{ steps.changed-files.outputs.added_files }}","updated":"${{ steps.changed-files.outputs.modified_files }}","deleted": "${{ steps.changed-files.outputs.deleted_files }}","renamed": "${{ steps.changed-files.outputs.renamed_files }}", "renamedTo": "${{ steps.changed-files.outputs.all_old_new_renamed_files }}"}'
        with:
          webhook_url: ${{ secrets.REFRESH_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.REFRESH_WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.REFRESH_WEBHOOK_AUTH }}
          data: '{"added": "${{ steps.changed-files.outputs.added_files }}","updated":"${{ steps.changed-files.outputs.modified_files }}","deleted": "${{ steps.changed-files.outputs.deleted_files }}","renamed": "${{ steps.changed-files.outputs.renamed_files }}", "renamedTo": "${{ steps.changed-files.outputs.all_old_new_renamed_files }}"}'
        uses: distributhor/workflow-webhook@v2
       

