name: Refresh Markdown Content
on: workflow_dispatch
  # Comment for local action dev
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - content/**

jobs:
  refresh:
    name: Refresh Content
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "2"

      - name: 📁 Get Changed Files in Content Directory
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: content/**

      - name: 🪝 Refresh Webhook
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          webhook_url: ${{ secrets.REFRESH_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.REFRESH_WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.REFRESH_WEBHOOK_AUTH }}
          data: '{ "content": "${{ steps.changed-files.outputs.all_modified_files }}" }'
        with:
          webhook_url: ${{ secrets.REFRESH_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.REFRESH_WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.REFRESH_WEBHOOK_AUTH }}
          data: '{ "content": "${{ steps.changed-files.outputs.all_modified_files }}" }'
        uses: distributhor/workflow-webhook@v2
       

